### ISSUE TITLE
Canot run the training script successfully

### ISSUE THREAD

**Issue by deyuf** [muye1202/quadruped_locomotion_project#1]
Hi muyue1202,

Thanks for sharing this project. I have an issue running the training script. After I ran the script, I got an error message which shows

```
Traceback (most recent call last):
  File "scripts/train.py", line 256, in <module>
    train_go1(headless=False)
  File "scripts/train.py", line 216, in train_go1
    runner.learn(num_learning_iterations=100000, init_at_random_ep_len=True, eval_freq=100)
  File "/home/deyu.fu/quadruped_locomotion_project/go1_gym_learn/ppo_cse/__init__.py", line 141, in learn
    actions_train = self.alg.act(obs[:num_train_envs], privileged_obs[:num_train_envs],
  File "/home/deyu.fu/quadruped_locomotion_project/go1_gym_learn/ppo_cse/ppo.py", line 86, in act
    self.transition.actions = self.actor_critic.act(obs_history).detach()
TypeError: act() missing 1 required positional argument: 'depth_obs'
```
After I checked the source code, I do see that the method ActorCritic.act requires a parameter called depth_obs, which is missing when this function is called. Can you help me fix this issue? Thanks!

**Comment by baoping-ma** [comment]
I have the same as your question, if need the insert the camera?

**Comment by muye1202** [comment]
Sorry guys I just saw this, let me take a look and get back to you ASAP

This might be due to the training and deployment pipeline are using the same actor_critic structure. Deployment requires camera input for depth observation (the depth_ons in the error message); I will try adding depth_obs to the pipeline.

**Comment by baoping-ma** [comment]
Excuse me, have you made any progress on the solution you mentioned (adding the depth_obs to the pipeline)? Thank you!

**Comment by baoping-ma** [comment]
Great job. Can you help with that? Appreciate very much.

TypeError: act() missing 1 required positional argument: 'depth_obs'

**Comment by baoping-ma** [comment]
> Hi muyue1202,嗨，muyue1202，
> 
> Thanks for sharing this project. I have an issue running the training script. After I ran the script, I got an error message which shows感谢您分享这个项目。我在运行训练脚本时遇到问题。运行脚本后，我收到一条错误消息，显示
> 
> ```
> Traceback (most recent call last):
>   File "scripts/train.py", line 256, in <module>
>     train_go1(headless=False)
>   File "scripts/train.py", line 216, in train_go1
>     runner.learn(num_learning_iterations=100000, init_at_random_ep_len=True, eval_freq=100)
>   File "/home/deyu.fu/quadruped_locomotion_project/go1_gym_learn/ppo_cse/__init__.py", line 141, in learn
>     actions_train = self.alg.act(obs[:num_train_envs], privileged_obs[:num_train_envs],
>   File "/home/deyu.fu/quadruped_locomotion_project/go1_gym_learn/ppo_cse/ppo.py", line 86, in act
>     self.transition.actions = self.actor_critic.act(obs_history).detach()
> TypeError: act() missing 1 required positional argument: 'depth_obs'
> ```
> 
> After I checked the source code, I do see that the method ActorCritic.act requires a parameter called depth_obs, which is missing when this function is called. Can you help me fix this issue? Thanks!在我检查源代码后，我确实看到方法 ActorCritic.act 需要一个名为 height_obs 的参数，但在调用该函数时缺少该参数。你能帮我解决这个问题吗？谢谢！

Have you solved this problem? How was it solved? Can you share? Thank you very much!

**Comment by muye1202** [comment]
Hi guys

Sorry for the delay, the `depth_obs` in `go1_gym_learn/ppo_cse/actor_critic.py` is required if you want the robot to have image observation as input during training. If you do not want to use visual info during training you can use `og_actor_critic.py` in the same folder, that file does not require `depth_obs`.

Thanks again for looking at our repo!

**Comment by popocheng** [comment]
如果訓練的時候不適用depth_obs，那麼訓練出的模型對部署是否會有影響，是否具有視覺能力？

**Comment by muye1202** [comment]
> 如果訓練的時候不適用depth_obs，那麼訓練出的模型對部署是否會有影響，是否具有視覺能力？

如果没有depth obs机器狗在训练阶段就不会使用image obs来训练policy，产出的模型input size也会不一样，也不会有视觉能力

**Comment by popocheng** [comment]
> > 如果訓練的時候不適用depth_obs，那麼訓練出的模型對部署是否會有影響，是否具有視覺能力？
> 
> 如果没有depth obs机器狗在训练阶段就不会使用image obs来训练policy，产出的模型input size也会不一样，也不会有视觉能力

能否提供完整的训练全流程，以适配该项目进行视觉部署？

**Comment by muye1202** [comment]
用这个文件训练应该是启用depth obs的：go1_gym_learn/ppo_cse/actor_critic.py，在模拟器中获取depth obs的代码应该是已经设置好了的。

你看看能不能跑？有问题的话我之后看看

多谢！

**Comment by muye1202** [comment]
> > > 如果訓練的時候不適用depth_obs，那麼訓練出的模型對部署是否會有影響，是否具有視覺能力？
> > 
> > 如果没有depth obs机器狗在训练阶段就不会使用image obs来训练policy，产出的模型input size也会不一样，也不会有视觉能力
> 
> 能否提供完整的训练全流程，以适配该项目进行视觉部署？

你如果有训练好的policy可以直接部署，go1
deploy文件夹里面的代码你看看能不能用

**Comment by popocheng** [comment]
> 用这个文件训练应该是启用depth obs的：go1_gym_learn/ppo_cse/actor_critic.py，在模拟器中获取depth obs的代码应该是已经设置好了的。
> 
> 你看看能不能跑？有问题的话我之后看看
> 
> 多谢！

该文件actor_critic.py确实有depth相关配置，但是__init__.py和ppo.py并未看到有对应的修改，能否提供你们用来训练视觉模型的完整版本，谢谢

**Comment by muye1202** [comment]
> 
> 
> 
> > 用这个文件训练应该是启用depth obs的：go1_gym_learn/ppo_cse/actor_critic.py，在模拟器中获取depth obs的代码应该是已经设置好了的。
> > 
> > 你看看能不能跑？有问题的话我之后看看
> > 
> > 多谢！
> 
> 该文件actor_critic.py确实有depth相关配置，但是__init__.py和ppo.py并未看到有对应的修改，能否提供你们用来训练视觉模型的完整版本，谢谢

好的我稍后看看，那现在这个script你能跑起来吗？还是会报错？报错的话可以把错误信息贴上来吗？

感谢

**Comment by popocheng** [comment]
> > > 用这个文件训练应该是启用depth obs的：go1_gym_learn/ppo_cse/actor_critic.py，在模拟器中获取depth obs的代码应该是已经设置好了的。
> > > 你看看能不能跑？有问题的话我之后看看
> > > 多谢！
> > 
> > 
> > 该文件actor_critic.py确实有depth相关配置，但是__init__.py和ppo.py并未看到有对应的修改，能否提供你们用来训练视觉模型的完整版本，谢谢
> 
> 好的我稍后看看，那现在这个script你能跑起来吗？还是会报错？报错的话可以把错误信息贴上来吗？
> 
> 感谢

如果直接运行train.py，和上面提到的报错是一样的：
Traceback (most recent call last):
  File "scripts/train.py", line 256, in <module>
    train_go1(headless=False)
  File "scripts/train.py", line 216, in train_go1
    runner.learn(num_learning_iterations=100000, init_at_random_ep_len=True, eval_freq=100)
  File "/home/deyu.fu/quadruped_locomotion_project/go1_gym_learn/ppo_cse/__init__.py", line 141, in learn
    actions_train = self.alg.act(obs[:num_train_envs], privileged_obs[:num_train_envs],
  File "/home/deyu.fu/quadruped_locomotion_project/go1_gym_learn/ppo_cse/ppo.py", line 86, in act
    self.transition.actions = self.actor_critic.act(obs_history).detach()
TypeError: act() missing 1 required positional argument: 'depth_obs'
按照上一条建议，不使用ppo，直接使用actor_critic，需要修改__init__相关部分。

**Comment by popocheng** [comment]
> > > > 用这个文件训练应该是启用depth obs的：go1_gym_learn/ppo_cse/actor_critic.py，在模拟器中获取depth obs的代码应该是已经设置好了的。
> > > > 你看看能不能跑？有问题的话我之后看看
> > > > 多谢！
> > > 
> > > 
> > > 该文件actor_critic.py确实有depth相关配置，但是__init__.py和ppo.py并未看到有对应的修改，能否提供你们用来训练视觉模型的完整版本，谢谢
> > 
> > 
> > 好的我稍后看看，那现在这个script你能跑起来吗？还是会报错？报错的话可以把错误信息贴上来吗？
> > 感谢
> 
> 如果直接运行train.py，和上面提到的报错是一样的： Traceback (most recent call last): File "scripts/train.py", line 256, in train_go1(headless=False) File "scripts/train.py", line 216, in train_go1 runner.learn(num_learning_iterations=100000, init_at_random_ep_len=True, eval_freq=100) File "/home/deyu.fu/quadruped_locomotion_project/go1_gym_learn/ppo_cse/**init**.py", line 141, in learn actions_train = self.alg.act(obs[:num_train_envs], privileged_obs[:num_train_envs], File "/home/deyu.fu/quadruped_locomotion_project/go1_gym_learn/ppo_cse/ppo.py", line 86, in act self.transition.actions = self.actor_critic.act(obs_history).detach() TypeError: act() missing 1 required positional argument: 'depth_obs' 按照上一条建议，不使用ppo，直接使用actor_critic，需要修改__init__相关部分。

能否提供视觉模型训练部分的完整流程，作为参考，谢谢

**Comment by muye1202** [comment]
好的，我稍等看一下，应该很好改

**Comment by popocheng** [comment]
> 好的，我稍等看一下，应该很好改

改好后烦请告知，感谢

**Comment by popocheng** [comment]
Hello, may I ask if you have made any progress on this issue?

**Comment by muye1202** [comment]
> Hello, may I ask if you have made any progress on this issue?

the code was not organized correctly for this part, I'm trying to find the original implementation, it's been some time since I ran this training, sorry about the delay

**Comment by popocheng** [comment]
Okay, looking forward to your progress so that everyone can use such a good job

**Comment by muye1202** [comment]
> Okay, looking forward to your progress so that everyone can use such a good job

The vision training module has been updated, can you try if it works now? Thanks again for notifying me about the problem, sorry about the delay.

Muye

**Comment by popocheng** [comment]
> > Okay, looking forward to your progress so that everyone can use such a good job
> 
> The vision training module has been updated, can you try if it works now? Thanks again for notifying me about the problem, sorry about the delay.
> 
> Muye

Thanks for doing a great job of updating, but when I run the train script, I encounter a new error:

```
Traceback (most recent call last):
  File "/media/nhy/office/gym/quadruped_locomotion_project-update/quadruped_locomotion_project-main/scripts/train.py", line 263, in <module>
    train_go1(headless=False)
  File "/media/nhy/office/gym/quadruped_locomotion_project-update/quadruped_locomotion_project-main/scripts/train.py", line 223, in train_go1
    runner.learn(num_learning_iterations=100000, init_at_random_ep_len=True, eval_freq=100)
  File "/media/nhy/office/gym/quadruped_locomotion_project-update/quadruped_locomotion_project-main/go1_gym_learn/ppo_cse/__init__.py", line 127, in learn
    obs, privileged_obs, depth_obs, obs_history = obs_dict["obs"], obs_dict["privileged_obs"], obs_dict["depth_obs"], obs_dict["obs_history"]
KeyError: 'depth_obs'
```

Does this mean that the depth camera is not enabled in env?

**Comment by muye1202** [comment]
Hi! sorry about going back and forth about this, let me check again; I currently do not have easy access to the server I used to train the model, so verification might be a bit troublesome, please bear with me and I will try to fix the problem.

Thanks
